services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    ports:
      - 3000:3000
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - 4000:4000
  