import Head from 'next/head'
import { Inter } from 'next/font/google'
import Box from '@mui/material/Box';
import Paper from '@mui/material/Paper';
import { Button } from '@mui/material';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Box
          sx={{
            display: 'flex',
            flexWrap: 'wrap',
            minHeight: '100vh',
            '& > :not(style)': {
              m: 'auto',
              width: 500,
              height: 500,
            },
          }}
        >
          <Paper elevation={3} sx={{ 
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            width: '100%',
            height: '100%',

           }} >
           <Box
          sx={{
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',

          }}
        >
            <Button fullWidth   color='primary' variant='contained'>
              <Link href={"/login"}>Login</Link>
            </Button>
            <br />
            <Button fullWidth color='primary' variant='outlined'><Link href={"/register"}>Register</Link></Button>
            </Box>
          </Paper>
        </Box>
      </>
    </>
  )
}
